---
 kind: pipeline
 name: default
 steps:
   - name: test
     image: golang:latest
     commands:
       - go test -v -bench=. .
---
kind: signature
hmac: 1cd72eb8fa084c9fb32898808ac6fdf1864321f079e0537c4d4d985eb5cc1fbe

...
